### ISSUE TITLE
JuliaCanvas image buffer type inconsistent across different OSs

### ISSUE THREAD

**Issue by urlicht** [JuliaGraphics/QML.jl#100]
- It seems like the buffer type of JuliaDisplay is inconsistent across OS
- On Windows, JuliaDisplay works with ARGB32 (UInt32, 0xAARRGGBB). However, on Ubuntu, it seems like the image buffer is actually in RGB32 (UInt32, 0xffRRGGBB)
- The same versions of QML (0.6.0) and Julia (1.5.3) were used on Windows (Windows 10) and Ubuntu (Ubuntu 18.04)

**Comment by barche** [comment]
Do you mean `JuliaDisplay` or `JuliaCanvas`? Because in the case of `JuliaDisplay` no arrays are involved directly? Could you provide an example of what goes wrong, exactly?

**Comment by urlicht** [comment]
Sorry about that, I meant `JuliaCanvas` I'll follow up with a simple example sometime later this week. Btw, thank you so much for developing this package. It makes cross-platform UI dev easy in Julia!

**Comment by barche** [comment]
I still have to test on Windows, but it seems the Qt image format was set to RGB, I switched it to ARGB but that will need a new release of the C++ code (jlqml_jll, should happen soon).

**Comment by ufechner7** [comment]
Should be fixed in QML 0,8
