### ISSUE TITLE
`force_model_update` should notify QML about length changes

### ISSUE THREAD

**Issue by bramtayl** [JuliaGraphics/QML.jl#149]
There are probably a lot of `AbstractVector` methods that it would be nice if `ListModel` supported, including

- `splice!`
- `deleteat!`

**Comment by bramtayl** [comment]
Alternatively, `force_model_update` could notify QML about length changes

**Comment by barche** [comment]
With the new `JuliaItemModel` all of this should be supported, see https://github.com/JuliaGraphics/QML.jl/blob/main/test/tableview.jl for an exhaustive example.
