### ISSUE TITLE
transfer to JuliaGraphics org

### ISSUE THREAD

**Issue by stevengj** [JuliaGraphics/QML.jl#163]
Might be worth transferring to the https://github.com/JuliaGraphics org (where the other GUI packages seem to live) to allow additional maintainers?

**Comment by ufechner7** [comment]
@barche Any comment? I could also become co-maintainer, if that should help.

**Comment by barche** [comment]
Yes, I am OK with a transfer to JuliaGraphics, and @ufechner7 you are welcome as co-maintainer. Any ideas what the steps to take are?

**Comment by ufechner7** [comment]
@stevengj Do you know how to organize a transfer to JuliaGraphics and adding me as co-maintainer?

**Comment by stevengj** [comment]
Someone has to add @barche as a [member of JuliaGraphics](https://github.com/orgs/JuliaGraphics/people), at which point they can [transfer the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization).

I'm not sure who has admin permissions on JuliaGraphics, maybe @timholy?

**Comment by ShalokShalom** [comment]
@stevengj He is already owner of that group. 

@barche You can transfer QML.jl yourself, still interested in doing that?

**Comment by ufechner7** [comment]
@barche Please do the transfer!
@stevengj How can I become member of the JuliaGraphics group (if that is required as co-maintainer)?

I really would like to create a new release that works with Julia 1.9.x which should not be so difficult as the main branch already works on Linux.

**Comment by ufechner7** [comment]
And the tests on Windows also pass, there is a warning that cleanup fails to a locked resource, but thats it:
```
┌ Warning: temp cleanup
│   exception =
│    IOError: rm("C:\\Users\\ufechner\\AppData\\Local\\Temp\\jl_0GpZ0a\\QmlJuliaExamples"): resource busy or locked (EBUSY)
│    Stacktrace:
│     [1] uv_error
│       @ .\libuv.jl:100 [inlined]
│     [2] rm(path::String; force::Bool, recursive::Bool)
│       @ Base.Filesystem .\file.jl:306
│     [3] rm(path::String; force::Bool, recursive::Bool)
│       @ Base.Filesystem .\file.jl:294
│     [4] rm
│       @ .\file.jl:273 [inlined]
│     [5] temp_cleanup_purge(; force::Bool)
│       @ Base.Filesystem .\file.jl:543
│     [6] temp_cleanup_purge
│       @ .\file.jl:535 [inlined]
│     [7] (::Base.var"#930#931")()
│       @ Base .\initdefs.jl:354
│     [8] _atexit(exitcode::Int32)
│       @ Base .\initdefs.jl:416
└ @ Base.Filesystem file.jl:547
     Testing QML tests passed
```

**Comment by ufechner7** [comment]
Should https://github.com/barche/QmlJuliaExamples.git also be moved? It is checkout out when running the tests of QML.jl ...

**Comment by barche** [comment]
Done at last :)
