### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by ufechner7** [JuliaGraphics/QML.jl#167]
The main branch works with Julia 1.9.2, the tests pass, so please create a new release. The tests fail for Julia 1.9.2 using the last release (0.7.1).

**Comment by ShalokShalom** [comment]
@barche The current release segfaults. 

Why would you release a version, that doesn't pass the tests in the first place? 

And why would you fix this issue, forget to release a fixed version, and then ignore an open issue about that for a month?

Can we help you with anything?

Thanks a lot 👍🏻

**Comment by ufechner7** [comment]
Well, the main branch works fine on Ubuntu 22.04:
```
/home/ufechner/.julia/packages/QML/dFnTL/test
     Testing QML tests passed 

(QML) pkg> st
Status `~/repos/QML/Project.toml`
  [2db162a6] QML v0.7.1 `https://github.com/barche/QML.jl.git#main`
```
using Julia 1.9.3.

I would create a new release that works on Linux even if it does not work on Windows yet and rather fix that later...

**Comment by ufechner7** [comment]
Justed tested QML#main on Windows, this also works, there is only a warning that the cleanup at the end fails due to a locked resource.

**Comment by barche** [comment]
Thanks for the tests! The delay was mainly because threaded rendering still doesn't work, but it's proving harder to debug than I thought, so I will go ahead with the release without this, after releasing CxxWrap 0.14 first and moving QML to the JuliaGraphics org.

**Comment by ufechner7** [comment]
Sounds great, thanks a lot!

For the future we can perhaps have an issue with a checklist of open items that should be fixed before a new release.

**Comment by ShalokShalom** [comment]
Some projects use labels for this. In case that makes sense, we could introduce universal patterns to do this, for the whole Julia Graphics project. So like: 

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label

**Comment by ufechner7** [comment]
Waiting for https://github.com/JuliaInterop/CxxWrap.jl/issues/369 to be resolved...

**Comment by barche** [comment]
I think https://github.com/JuliaInterop/libcxxwrap-julia/pull/132 will fix the problem with CxxWrap.

**Comment by ufechner7** [comment]
CxxWrap 0.14 is released. So creating a new release of QML should be possible now.

**Comment by barche** [comment]
Adding a todo list so you don't keep wondering ;)

- [ ] Change license to MIT
- [ ] Small change in `qputenv` for Qt 6.5 compatibility
- [ ] Move to JuliaGraphics
- [ ] Investigate some Wayland issues

**Comment by barche** [comment]
It PR #170 works out then this should soon be done.

**Comment by barche** [comment]
Sorry but I added one more task, it seems a shame to finally release this based on an old Qt when 6.5 came out in the mean time and is LTS. I expect this to take 2 days max.

**Comment by ShalokShalom** [comment]
I would invite you, to then announce it on the forums, if you want. 
A big release reveal, and the move to JuliaGraphics. 👍🏻

**Comment by barche** [comment]
Final test is running now on PR #170, if that checks out I think we're ready for release.

**Comment by ufechner7** [comment]
@barche Any update on this? Fix the test failure and make a new release, or ignore the test failure and make a release as you suggested in the PR ?

**Comment by barche** [comment]
@JuliaRegistrator register

**Comment by barche** [comment]
See https://github.com/JuliaRegistries/General/pull/92090

**Comment by ufechner7** [comment]
Some things are not easy! Luckily you are persistent.

**Comment by barche** [comment]
The release is now in the general registry and announced on Discourse: https://discourse.julialang.org/t/ann-qml-jl-v0-8/104328?u=barche
