### ISSUE TITLE
Crash on Windows and Julia 1.9.2

### ISSUE THREAD

**Issue by f-ij** [JuliaGraphics/QML.jl#168]
I'm getting the error:

Exception: EXCEPTION_ACCESS_VIOLATION at 0xef73f73 -- _ZN7qmlwrap11JuliaCanvas5paintEP8QPainter at C:\Users\User\.julia\artifacts\d9cb3df9816fda8a255f45de49b0439a013a77fc\bin\libjlqml.dll (unknown line)
in expression starting at c:\Users\User\Julia Projects\Project.jl\examples\main.jl:38
Allocations: 31536727 (Pool: 31516531; Big: 20196); GC: 44

**Comment by ufechner7** [comment]
Did you try to install the main branch:
```
]
add QML#main
```
This works for me with Julia 1.9.3 on Windows and Linux.

**Comment by ufechner7** [comment]
Perhaps this can be closed now that 0.8 is released?
