### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaGraphics/QML.jl#169]
Hello :)

Thanks a thousand times for this wonderful, wonderful package. I am a total fan of QML and advanced languages like Julia. 

![Screenshot_20230824_182548](https://github.com/barche/QML.jl/assets/6344099/0606d8b4-7d55-49a8-86da-daa5bc7bef97)

I am not able to update the About section, so I just wanna raise awareness, that this doesnt speak (yet) about Qt6. 

Thanks a lot, that you develop this!

**Comment by ufechner7** [comment]
Well, who can update the about section? Just @barche , or who else?

**Comment by barche** [comment]
Done :)
