### ISSUE TITLE
QML.jl failing on upcoming beta2 (and crashing for 1.10), though both seemingly false alarms...

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaGraphics/QML.jl#196]
I assumed, wrongly, it's because of CxxWrap (v0.15.0) but it passes tests on its own:

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bdc7fb7_vs_bd47eca/CxxWrap.primary.log

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bdc7fb7_vs_bd47eca/QML.primary.log

Unless it's because for QML:
```
⌅ [1f15a43c] + CxxWrap v0.14.2
[..]
⌅ [3eaa8342] + libcxxwrap_julia_jll v0.11.2+1
[..]
Failed to precompile CxxWrap [1f15a43c-97ca-5a2a-ae31-89f07a497df4] to "/home/pkgeval/.julia/compiled/v1.11/CxxWrap/jl_UfRyPa".
julia: /source/src/array.c:266: ijl_array_ptr_1d_push: Assertion `(((((jl_taggedvalue_t*)((char*)(a) - sizeof(jl_taggedvalue_t)))->header) & ~(uintptr_t)15)==(uintptr_t)(jl_array_any_type))' failed.
```

But then it's still a question, why isn't latest QML tested with all latest dependencies, such as CxxWrap, by PkgEval?

I see this when I install packages, I sometime get older versions (usually something blocking), and at least in one case got non-latest, but nothing was blocking upgrade to latest...  I think it may just be a "bug" in Pkg, and fixing that might fix PkgEval.

Ideally of course older versions of CxxWrap would also work...

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bdc7fb7_vs_bd47eca/report.html

https://github.com/JuliaLang/julia/pull/54112#issuecomment-2063288593

If older versions of CxxWrap are known to break on newer Julias (hus happened) then is there another workaround, changing in the registry so that for certain Julias at least some version needs to be installed? Because if even PkgEval fails, and Pkg doesn't install correctly, then this can for sure happen to regular users...

**Comment by KristofferC** [comment]
> why isn't latest QML tested with all latest dependencies, such as CxxWrap, by PkgEval?

Because of https://github.com/JuliaGraphics/QML.jl/blob/8dc510d4d7ebaebc9a18ca1d927b88f6745137d7/Project.toml#L18

**Comment by barche** [comment]
Upgrading to CxxWrap 0.15 requires rebuilding also the `jlqml` binary component against the latest `libcxxwrap-julia`. I'll take the opportunity to first deal with #195 .

**Comment by ufechner7** [comment]
Is this a bug or a feature request? If it is a bug, can it be fixed by updating `Project.toml` of QML.jl only?

**Comment by ufechner7** [comment]
Just tested QML 0.9.1 with Julia 1.10.5, and the tests pass. Therefore I close this issue. If there still is an issue with a different configuration, please comment and I will re-open.
