### ISSUE TITLE
plot.jl gives segfault when selecting GR backend

### ISSUE THREAD

**Issue by KajWiik** [JuliaGraphics/QML.jl#27]
```julia 
julia> include(joinpath(Pkg.dir("QML"),"example","plot.jl"))

signal (11): Segmentation fault
while loading /home/kjwiik/.julia/v0.5/QML/example/plot.jl, in expression starting on line 45
__libc_siglongjmp at /build/glibc-Qz8a69/glibc-2.23/setjmp/longjmp.c:30
unknown function (ip: 0x7f6d607c0fe1)
png_error at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct_2 at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
unknown function (ip: 0x7f6d607c118e)
cairo_surface_write_to_png at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7f6d60761387)
gks_cairoplugin at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7f6d60e9ba59)
gks_close_ws at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gks_emergency_close at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gr_emergencyclosegks at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
_show at /home/kjwiik/.julia/v0.5/Plots/src/backends/gr.jl:1090
display at /home/kjwiik/.julia/v0.5/QML/src/QML.jl:111
unknown function (ip: 0x7f6d91820bd6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
plotsin at /home/kjwiik/.julia/v0.5/QML/example/plot.jl:33
unknown function (ip: 0x7f6d917d1a92)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_call at /home/centos/buildbot/slave/package_tarball64/build/src/jlapi.c:126
_ZN7qmlwrap8JuliaAPI4callERK7QStringRK5QListI8QVariantE at /home/kjwiik/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7f6d90f76405)
_ZN7qmlwrap8JuliaAPI11qt_metacallEN11QMetaObject4CallEiPPv at /home/kjwiik/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7f6d902c1318)
unknown function (ip: 0x7f6d9024667b)
unknown function (ip: 0x7f6d90247ebb)
_ZN3QV413QObjectMethod12callInternalEPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
_ZN3QV47Runtime12callPropertyEPNS_15ExecutionEngineEiPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
unknown function (ip: 0x7f6d68024afc)
unknown function (ip: 0x7f6d901fef36)
unknown function (ip: 0xb56d51471f3b2bff)
Allocations: 18685626 (Pool: 18683953; Big: 1673); GC: 33
Segmentation fault (core dumped)
`

**Comment by barche** [comment]
Strange, it crashes in libpng. Does GR outside of QML create a png image?

@jheinen have you seen this before?

**Comment by KajWiik** [comment]
Yes, the following works fine:
```julia
julia> using GR
julia> beginprint("/tmp/foo.png")
julia> plot(rand(10))
julia> endprint()
```

**Comment by jheinen** [comment]
```julia
include(joinpath(Pkg.dir("QML"),"example","plot.jl"))
```
... works for me (OS X).

Did your download the latest GR run-time?

```julia
ENV["GRDIR"]=""
Pkg.build("GR")
```
<img width="912" alt="screen shot 2016-12-10 at 21 54 41" src="https://cloud.githubusercontent.com/assets/5718244/21076112/927d569c-bf23-11e6-9823-b671000355b5.png">

**Comment by jheinen** [comment]
@barche : We should probably change this demo (for GR) to use the new `JuliaPaintedItem` mechanism, because results in a two orders of magnitude speed improvement

**Comment by KajWiik** [comment]
I didn't but even doing so I get segfault:

```julia
julia> ENV["GRDIR"]=""
""
julia> Pkg.build("GR")
INFO: Building GR
INFO: Downloading pre-compiled GR 0.22.0 Ubuntu binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.1M  100 38.1M    0     0  4030k      0  0:00:09  0:00:09 --:--:-- 4108k
julia> include(joinpath(Pkg.dir("QML"),"example","plot.jl"))
signal (11): Segmentation fault
....
```

**Comment by jheinen** [comment]
... works find for me (on an Ubuntu 16.04 VM) with QML + CxxWrap + GR master branches. But as each frame is rendered as an image, is much slower the the  native QML + GR variant.

<img width="1296" alt="screen shot 2016-12-11 at 10 43 08" src="https://cloud.githubusercontent.com/assets/5718244/21079319/24207f50-bf8f-11e6-8c98-f8942a7c798a.png">

**Comment by barche** [comment]
@KajWiik Just to ensure that it only happens because of QML, could you try the following in a Julia terminal:
```julia
using Plots
gr(size=(512,512))
x = 0:π/100:π
plot(x,sin(x))
savefig("test.png")
```
And see if that works without crashing? Also, what platform/linux distro are you on?

**Comment by KajWiik** [comment]
@barche That works perfectly. This is on a Ubuntu 16.04 oldish Lenovo T410 laptop (i5 M520). I'll test tomorrow on a i7 desktop.

**Comment by KajWiik** [comment]
Äh, I forgot to Pkg.checkout(), after checking out and building GR, QML and CxxWrap the example works fine. Sorry...and thanks!

**Comment by barche** [comment]
OK, good to know, thanks!

**Comment by ufechner7** [comment]
It doesn't work for me (Ubuntu 16.04). Any idea:

```
julia> include(joinpath(Pkg.dir("QML"),"example","plot.jl"))

signal (11): Segmentation fault
while loading /home/ufechner/.julia/v0.5/QML/example/plot.jl, in expression starting on line 44
__libc_siglongjmp at /build/glibc-t3gR2i/glibc-2.23/setjmp/longjmp.c:30
unknown function (ip: 0x7fd68489efe1)
png_error at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct_2 at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
unknown function (ip: 0x7fd68489f18e)
cairo_surface_write_to_png at /home/ufechner/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7fd68483f387)
gks_cairoplugin at /home/ufechner/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7fd684f81a59)
gks_close_ws at /home/ufechner/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gks_emergency_close at /home/ufechner/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gr_emergencyclosegks at /home/ufechner/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
_show at /home/ufechner/.julia/v0.5/Plots/src/backends/gr.jl:1090
display at /home/ufechner/.julia/v0.5/QML/src/QML.jl:109
unknown function (ip: 0x7fd6bddb12b6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
plotsin at /home/ufechner/.julia/v0.5/QML/example/plot.jl:32
unknown function (ip: 0x7fd6bdd62162)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_call at /home/centos/buildbot/slave/package_tarball64/build/src/jlapi.c:126
_ZN7qmlwrap8JuliaAPI4callERK7QStringRK5QListI8QVariantE at /home/ufechner/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7fd6bd4efcd5)
_ZN7qmlwrap8JuliaAPI11qt_metacallEN11QMetaObject4CallEiPPv at /home/ufechner/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7fd6bc826318)
unknown function (ip: 0x7fd6bc7ab67b)
unknown function (ip: 0x7fd6bc7acebb)
_ZN3QV413QObjectMethod12callInternalEPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
_ZN3QV47Runtime12callPropertyEPNS_15ExecutionEngineEiPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
unknown function (ip: 0x7fd686590efc)
unknown function (ip: 0x7fd6bc763f36)
unknown function (ip: 0x36eca3a2df8a87ff)
Allocations: 21987251 (Pool: 21985524; Big: 1727); GC: 39
Segmentation fault (core dumped)
ufechner@tuxedo:~$ 
```

**Comment by KajWiik** [comment]
@ufechner7 Exactly the same problem I had, try Pkg.checkout(x);Pkg.build(x) for GR,CxxWrap,QML. Works fine now.

**Comment by ufechner7** [comment]
@KajWiik Unluckily your suggestion does not help me. Any idea, how to debug this further?

**Comment by barche** [comment]
Does it work if you run it stand-alone, i.e. something like:
```
julia $HOME/.julia/v0.5/QML/example/plot.jl
```
?

**Comment by KajWiik** [comment]
@barche Hmm, now I get segfault again too:
```julia
kjwiik@T410:~$ julia $HOME/.julia/v0.5/QML/example/plot.jl

signal (11): Segmentation fault
while loading /home/kjwiik/.julia/v0.5/QML/example/plot.jl, in expression starting on line 44
__libc_siglongjmp at /build/glibc-t3gR2i/glibc-2.23/setjmp/longjmp.c:30
unknown function (ip: 0x7f97a3c86fe1)
png_error at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct_2 at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct at /usr/lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
unknown function (ip: 0x7f97a3c8718e)
cairo_surface_write_to_png at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7f97a3c27387)
gks_cairoplugin at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7f97a86d1a59)
gks_close_ws at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gks_emergency_close at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
gr_emergencyclosegks at /home/kjwiik/.julia/v0.5/GR/src/../deps/gr/lib/libGR.so (unknown line)
_show at /home/kjwiik/.julia/v0.5/Plots/src/backends/gr.jl:1090
display at /home/kjwiik/.julia/v0.5/QML/src/QML.jl:109
unknown function (ip: 0x7f97d904fb26)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
plotsin at /home/kjwiik/.julia/v0.5/QML/example/plot.jl:32
unknown function (ip: 0x7f97d9000a52)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_call at /home/centos/buildbot/slave/package_tarball64/build/src/jlapi.c:126
_ZN7qmlwrap8JuliaAPI4callERK7QStringRK5QListI8QVariantE at /home/kjwiik/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7f97d87b46b5)
_ZN7qmlwrap8JuliaAPI11qt_metacallEN11QMetaObject4CallEiPPv at /home/kjwiik/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7f97d7af4318)
unknown function (ip: 0x7f97d7a7967b)
unknown function (ip: 0x7f97d7a7aebb)
_ZN3QV413QObjectMethod12callInternalEPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
_ZN3QV47Runtime12callPropertyEPNS_15ExecutionEngineEiPNS_8CallDataE at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (unknown line)
unknown function (ip: 0x7f97b0000c4c)
unknown function (ip: 0x7f97d7a31f36)
unknown function (ip: 0x3fb6d3ad290e8eff)
Allocations: 18030474 (Pool: 18028849; Big: 1625); GC: 30
Segmentation fault (core dumped)
```

**Comment by ufechner7** [comment]
I upgraded to Qt 5.7, and now I get a different error:
```
julia> include("example/glvisualize.jl")
ERROR: LoadError: Could not find function initialize_signals
 in load_qml_app(::String, ::Array{Any,1}, ::Array{Any,1}) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
while loading /home/ufechner/.julia/v0.5/QML/example/glvisualize.jl, in expression starting on line 39
julia> 
```
Any idea?

**Comment by ufechner7** [comment]
I also get the following message when building QML, even though I have installed GLVisualize:
```julia
[ 69%] Linking CXX shared library libqmlwrap.so
[100%] Built target qmlwrap
Install the project...
-- Install configuration: "Release"
-- Installing: /home/ufechner/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so
-- Set runtime path of "/home/ufechner/.julia/v0.5/QML/deps/usr/lib/libqmlwrap.so" to "/home/ufechner/.julia/v0.5/QML/deps/usr/lib:/home/ufechner/.julia/v0.5/CxxWrap/deps/usr/lib/cmake/../:/home/ufechner/Qt5.7.0/5.7/gcc_64/lib"
GLVisualize support disabled. To use it, install the GLVisualize package.

julia> 

```

**Comment by barche** [comment]
Did you do `Pkg.checkout("GLWindow")`? The glvisualize example requires a non-released adaptation there.

**Comment by ufechner7** [comment]
All the examples, mentioned on https://discourse.julialang.org/t/qml-jl-first-release/770 are working now. I am not sure, what the minimal required version of QT is, but for me it works after upgrading from QT 5.5 to QT 5.7 and doing a Pkg.checkout and Pkg.build for GLWindow, GR, QML and CxxWrap .

**Comment by barche** [comment]
OK, I never tested with Qt 5.5, maybe that somehow triggers it. I don't think checkout on QML and CxxWrap has anything to do with this segfault, but if you do checkout QML you must also checkout CxxWrap and vice-versa.

@KajWiik Does `Pkg.test("QML")` pass on the config that gives the plot.jl segfault?

**Comment by jheinen** [comment]
@barche :  I'm trying to track the mouse position and set a text widget (id: position) using `@qmlset qmlcontext().position = "$x $y"`. What's the trick?

https://github.com/jheinen/GR.jl/commit/3f2c44f2b7f966b72cee237a07e56f57d75c7c55

**Comment by barche** [comment]
@jheinen I would use a context property, such as `position` in https://github.com/barche/QML.jl/blob/master/example/sketch.jl

Then, in the QML you can access the value directly:
https://github.com/barche/QML.jl/blob/master/example/qml/sketch.qml#L19

Reaching into the QML tree from Julia is deliberately impossible, see issue #25

**Comment by KajWiik** [comment]
@barche Tests pass:
```julia
julia> Pkg.test("QML")
INFO: Testing QML
running test functions.jl...
running test julia_arrays.jl...
julia_array = Any["A","TEST2","Added",2,3]
move_array = [0,1,5,6,7,2,3,4,8,9]
custom_list = ListElem[ListElem("a",1),ListElem("b",5),ListElem("ten",10)]
running test julia_object.jl...
running test julia_signal.jl...
running test libinfo.jl...
qt_prefix_path() = "/usr"
running test listviews.jl...
julia_array = Any["TEST",1,2.2]
running test properties.jl...
running test qqmlcomponent.jl...
running test qquickview.jl...
running test qtimer.jl...
INFO: QML tests passed
```
but `include(joinpath(Pkg.dir("QML"),"example","plot.jl"))` fails. Heisenbug?
I'm not ready to use QT beyond versions provided by deb packagea ..back to Gtk...

**Comment by ufechner7** [comment]
@KajWiik With which QT version did you have this problem?

**Comment by KajWiik** [comment]
@ufechner7 Ubuntu Xenial 16.04 standard package gives 
```
ii  libqt5core5a:amd64 5.5.1+dfsg-16ubuntu7.2 amd64        Qt 5 core module
```

**Comment by barche** [comment]
Just tested on a VirtualBox Ubuntu 16.04, there all the tests and examples segfault even though QML apps work fine in qmlscene... I'll have to investigate further, especially since the same happens on the Raspberry Pi and I want it working there too. Must be something stupid, since it works on Arch, Fedora, OS X and Windows...

**Comment by barche** [comment]
I'm wondering if this is due to an ABI-incompatibility between C++11 and legace C++. Anyone know if the Ubuntu Qt5 libs are compiled with --std=c++11?

**Comment by barche** [comment]
Frustratingly, this seems to be impossible to debug in a VirtualBox, where even the simplest QML example just crashes.

@KajWiik Could you test if clicking the "Push Me" button in `example/gui.jl` works? When I booted using a live USB, this crashed with a LLVM ERROR for me. Also, I created a minimalistic QML test here:
https://github.com/barche/LoadQML.jl

Install and try using:
```julia
Pkg.clone("https://github.com/barche/LoadQML.jl.git")
Pkg.build("LoadQML")
Pkg.test("LoadQML")
```
If that one fails, there is little hope to get QML.jl working on Ubuntu 16.04.

**Comment by barche** [comment]
@KajWiik @jheinen 

OK, I was finally able to reproduce the problem, it is related to binary incompatibility between the Ubuntu system libs and the GR binaries. You can get the same crash using the following script:

```julia
using Plots
gr()
x = 0:π/100:π
f = sin(x)
plt = plot(x,f,ylims=(-5,5),show=false)
buf = IOBuffer()
Base.show(buf, MIME"image/png"(), plt)
```

Run this using

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpng12.so.0 julia script-name.jl
```

and you get the same crash, without the `LD_PRELOAD` it runs. I believe Qt5 pulls in the same system libpng, hence the crash. This would also happen for any other package that directly or indirectly pulls in libpng before loading GR.

Note that all of this was done using the PPA version of Julia, the regular binary from julialang.org doesn't pass the QML tests and bails out with an LLVM_ERROR, probably also because of another binary compatibility.

Compiling GR from source is what I'd recommend for this specific case.

The VirtualBox trouble mentioned previously is now tracked here: https://github.com/JuliaLang/julia/issues/19606

**Comment by ufechner7** [comment]
Just for the record: Everything works fine on Ubuntu 16.04, if you install QT 5.7 using the official installer as described here: https://wiki.qt.io/Install_Qt_5_on_Ubuntu
I am using the regular binary of julia from julialang.org. Compiling GR from source is not required.

**Comment by ufechner7** [comment]
I forgot to mention, that I had to add the following lines to .bashrc 
```bash
export Qt5Widgets_DIR=$HOME/Qt5.7.0/5.7/gcc_64/lib/cmake/Qt5Widgets
export Qt5Quick_DIR=$HOME/Qt5.7.0/5.7/gcc_64/lib/cmake/Qt5Quick
export CMAKE_PREFIX_PATH=$HOME/Qt5.7.0/5.7/gcc_64
```

**Comment by barche** [comment]
OK, that makes sense too, if it's a precompiled binary they probably link in things like libpng statically and there is no conflict.

**Comment by jheinen** [comment]
@ufechner : Thank you for testing. I did the same tests with Qt 5.7.1 on macOS X, and, with the **official** distribution from qt.io, everything works (QML + GR) fine. Still some problems with Retina resolution - but that's related to GR.

Will now try the generic Qt 5.7.1 Linux binary on CentOS 7 ...

@barche : Yes, the Qt developers are using their own static PNG library - we made the same decision (for GR) month ago. I just wonder whether I should eliminate the `libpng` code from GR and implement a minimalistic PNG writer routine ...

**Comment by barche** [comment]
@jheinen I wouldn't go for that solution, but rather try to automate building the GR dependency (controlled by an environment variable) so users can choose to build their own binary in cases like this. I haven't checked if the GR source maybe already has this? An additional benefit is that you can use something like Travis to build a binary release automatically.

**Comment by jheinen** [comment]
@barche : There are already GR packages for most Linux flavours: http://software.opensuse.org/download.html?project=science:gr-framework&package=python-gr

Also, if all dependencies are installed, the user should be able to build his own GR distribution. We just wanted to make it easier by providing pre-buyild binaries ...

**Comment by ufechner7** [comment]
Works fine now.
