### ISSUE TITLE
some more details on use of setindex! in ListModels

### ISSUE THREAD

**Issue by Ph0non** [JuliaGraphics/QML.jl#35]
With interest i read your explainations in https://github.com/barche/QML.jl#listmodel and to change data in a ListModel from QML itself. This is exactly what i need for a new feature for my own code.

For editing a TableView i use code from [stackoverflow](http://stackoverflow.com/questions/23856114/in-qml-tableview-when-clicked-edit-a-data-like-excel) which works fine (see [here](https://github.com/Ph0non/NuclideVector/blob/79cb00df8a92f9aea1d26593deb9674b0ffb4f09/nvqt2/ShowNV.qml#L51-L99)). This returns (with no surprise) `Null setter for role "2016", not changing value` because it is only readable.

Like in your example I added `setindex!` to `addrole`
```
addrole(nuclidesModel, year, n -> round(n.values[i],2), setindex!)
```
(see [here](https://github.com/Ph0non/NuclideVector/blob/79cb00df8a92f9aea1d26593deb9674b0ffb4f09/nvqt2/calcnv.jl#L22) and [here](https://github.com/Ph0non/NuclideVector/blob/79cb00df8a92f9aea1d26593deb9674b0ffb4f09/nvqt2/calcnv.jl#L54))

But obviously i miss something, because this results in a segfault
```
ErrorException("type Float64 has no field values")
```

**Comment by barche** [comment]
The problem here is that the standard `setindex!` will set the entire nuclide for a row. Here, it is a role for a year so I think you need something like this (untested):
```julia
addrole(nuclidesModel, year, n -> round(n.values[i],2), (n, newval, row) -> n[row].values[i] = newval)
```

`n` is the list of nuclides, `row` the row in the table (converted to 1-based) and `newval` is the value for the role, which is one of the years here and so I guess a `Float64`.

**Comment by Ph0non** [comment]
Seems to work. I will test later more to see if it fits all. Thanks for you quick response.

It would be a great example for further use of ListModels in ListView and TableView. At least i will make an example for your repo, if this would be fine for you.

**Comment by barche** [comment]
Sure, more examples are always welcome, feel free to also improve the readme if it lacks clarity.

**Comment by ufechner7** [comment]
In 0.8 ListModel were removed.
