### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by jheinen** [JuliaGraphics/QML.jl#36]
I tried to build QML with an existing Qt5 installation. This works fine on macOS X and Ubuntu, but it fails on Windows 10. The QT_ROOT setting seems to be ignored during the build step. In our case, I wanted to use an existing Qt5 distribution located in S:\Qt\5.7.0. What is the trick?

**Comment by barche** [comment]
You also need to set `ENV["BUILD_ON_WINDOWS"] = 1`, which affects both CxxWrap and QML, because they both must be built with the same compiler. It may also be necessary to remove the usr dir in the deps directories of QML and CxxWrap.

**Comment by jheinen** [comment]
Unfortunately, that doesn't help. The `cmake` files didn't find the locally installed VC compiler, although `CL` was in the search path.

**Comment by barche** [comment]
Just to be sure: you do have the cmake executable in your path, right? What version of visual studio are you using? I use version 2015 and didn't have to do anything to get CMake to find it on either my own machine or appveyor.

**Comment by jheinen** [comment]
Yes, cmake was in the path, but I only have version 2010 installed.

**Comment by barche** [comment]
Aha, the C++ code in CxxWrap doesn't compile on visual studio before version 2015 (service pack 2 I think, community edition is fine), because of the C++11 requirements. The reason it's not found is because I set the generator to `Visual Studio 14 2015` in build.jl.

**Comment by ufechner7** [comment]
Perhaps this can be closed now that 0.8 is released?
