### ISSUE TITLE
wrong plot size in gr.jl example on a mac retina display

### ISSUE THREAD

**Issue by piever** [JuliaGraphics/QML.jl#48]
Not sure if it's a GR or a QML issue. On my machine (mac OS using built in retina display) when I run the example "gr.jl", the plot has the wrong size:

<img width="794" alt="screen shot 2017-09-24 at 18 52 39" src="https://user-images.githubusercontent.com/6333339/30785146-c7348f40-a159-11e7-93bd-ac6589f5b985.png">

For it to be of a more appropriate size I need to manually change [this line](https://github.com/barche/QML.jl/blob/master/example/gr.jl#L32) to 

`plt[:size] = (width(dev)/2, height(dev)/2)`

<img width="799" alt="screen shot 2017-09-24 at 18 52 07" src="https://user-images.githubusercontent.com/6333339/30785189-85e47144-a15a-11e7-9c72-78ee119d0041.png">

I wonder if it's a bug with pixel doubling in retina display. I don't know how the plot would look like on another machine.

**Comment by barche** [comment]
This is definitely due to the Retina display. In the console there should be output like this:

```
pixel ratio: 1.0
```

Hopefully with a value different from 1.0, can you confirm that and tell me the value (presumably 2 or 0.5)?

**Comment by piever** [comment]
I see, so you should divide `width(dev)` and `height(dev)` by the pixel ratio to get the correct size.

Here's my output:

```julia
julia> include(joinpath(Pkg.dir("QML"), "example", "gr.jl"))
WARNING: redefining constant screeninfo
pixel ratio: 2.0
screeninfo.pixel_ratio = 2.0
"Example of GR.jl integration\n"
```

**Comment by piever** [comment]
Just noticed, that's the solution chosen in GR.jl, see here:

https://github.com/jheinen/GR.jl/blob/master/examples/qml_plots_ex.jl#L27

**Comment by barche** [comment]
OK, cool, I'll update the example also with some control points, but I still need to work out some problems with the coordinate conversion.

**Comment by ufechner7** [comment]
Should work in QML 0.8
