### ISSUE TITLE
qmlscene support: how to install org.julialang

### ISSUE THREAD

**Issue by treygreer** [JuliaGraphics/QML.jl#66]
Hi, hope all is well with you.

I'd like to debug my gui layout with qmlscene.  Is this possible?   If I just naively run qml scene on a qml file with org.julialang content, I get  'module org.julialang is not installed'.

I see that qmlscene has -I <path> and -P <path> command line options.  Is is possible that one of those options could install org.julialang?

**Comment by barche** [comment]
Sorry for missing this, you probably figured it out by now, but it's not possible to use qmlscene (as far as I know at least) since the org.julialang module is loaded by loading the QML package in Julia.

**Comment by ufechner7** [comment]
Perhaps this can be closed now?
