### ISSUE TITLE
gr example depends on Qt4

### ISSUE THREAD

**Issue by treygreer** [JuliaGraphics/QML.jl#69]
The gr example gives me 
`GKS: libQtGui.so.4: cannot open shared object file: No such file or directory`

I'm on CentOS 8 where Qt4 is not readily available.  The Plots GR code in general no longer depends on Qt4, so this is a bit of a mystery.  I'm digging into it, but any hints would be greatly appreciated.  Thanks!

**Comment by treygreer** [comment]
Seems the fix is to add ENV["GKS_QT_VERSION"]=5 to gr.jl.  I'll submit a pull request shortly.

**Comment by ufechner7** [comment]
With QML 0.8 the example just works.
