### ISSUE TITLE
Cannot run GR examples on macOS

### ISSUE THREAD

**Issue by tiagopereira** [JuliaGraphics/QML.jl#92]
I can't seem to run the GR part of the QML examples, which was really what I was after when using QML. With a fresh installation of Julia 1.4.2, I installed the following:

    (@v1.4) pkg> add QML GR Plots CxxWrap Observables ColorTypes IJulia
    (...)

Trying to run the example `canvas_and_gr.jl`, it doesn't seem to find QtWidgets:

```
julia> include(joinpath(Pkg.dir("QML"), "example", "canvas_and_gr.jl"))
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Installed library rpath /Users/myuser/.julia/artifacts/faa3d85040dd71e53e98e8fc6d0ee4fd6ab4d8b4/Frameworks to plugin /Users/myuser/.julia/packages/GR/8mv9N/src/../deps/gr/lib/qt5plugin.so
GKS: dlopen(/Users/myuser/.julia/packages/GR/8mv9N/src/../deps/gr/lib/qt5plugin.so, 1): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/myuser/.julia/packages/GR/8mv9N/deps/gr/lib/qt5plugin.so
  Reason: image not found
```
If I try to run an example with GR a second time, it retries to do the rpath install once more, and gives a larger error, but ultimately the same `Image not found` for QtWidgets. 

Any idea on how I can fix this?

**Comment by ufechner7** [comment]
Working fine for me on Ubuntu 18.04:
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using QML
julia> using Pkg

julia> include(joinpath(Pkg.dir("QML"), "example", "canvas_and_gr.jl"))
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import QML; joinpath(dirname(pathof(QML)), "..", paths...)`.
└ @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:543

julia>

**Comment by barche** [comment]
The problem is that by default the GR library can't find the Qt5 library. There is a hack in QML.jl to attempt to fix this by setting rpath, (the `Installed library rpath` line) but it seems to be failing for some reason. The proper solution will be to have BinaryBuilder-provided GR binaries that are built against the Qt5 libraries from BinaryBuilder, maybe @jheinen has an update on this, or a good workaround?

**Comment by pazner** [comment]
This may be related — I get the following warning when running `using QML, GR` (Julia 1.5.0 on macOS).
```
error:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/
usr/bin/install_name_tool: for:
/Users/will/.julia/packages/GR/8mv9N/src/../deps/gr/lib/qt5plugin.so (for
architecture x86_64) option "-add_rpath
/Users/will/.julia/artifacts/faa3d85040dd71e53e98e8fc6d0ee4fd6ab4d8b4/
Frameworks" would duplicate path, file already has LC_RPATH for:
/Users/will/.julia/artifacts/faa3d85040dd71e53e98e8fc6d0ee4fd6ab4d8b4/
Frameworks ┌ Warning: Error requiring GR from QML: │ failed process:
Process(`install_name_tool -add_rpath
/Users/will/.julia/artifacts/faa3d85040dd71e53e98e8fc6d0ee4fd6ab4d8b4/
Frameworks
/Users/will/.julia/packages/GR/8mv9N/src/../deps/gr/lib/qt5plugin.so`,
ProcessExited(1)) [1]

[...long stack trace omitted...]
```
Everything still works otherwise, but it would be great to avoid this warning somehow.

**Comment by ufechner7** [comment]
Is this still an issue when using QML 0.8?

**Comment by barche** [comment]
No, the use of GR_jll fixed this.
