### ISSUE TITLE
Listmodel insert transitions

### ISSUE THREAD

**Issue by bramtayl** [JuliaGraphics/QML.jl#96]
I'm struggling how to describe the issue here, but it seems like there's something not right about the transitions triggered by a listmodel `insert`, because the examples in the tutorial here aren't quite working:

https://doc.qt.io/qt-5/qml-qtquick-viewtransition.html

I think it might be an issue with the code here:

https://github.com/barche/jlqml/blob/1e2fb83a7805b7ee7048b6cb1d22fa4bcf59095b/listmodel.cpp#L95

which seems to be triggering a combination of `add` and `move` transitions, instead of `displace` transitions. On the other hand, `remove` seems to be triggering `displace` transitions as expected.

**Comment by ufechner7** [comment]
Is this still an issue with QT6 and QML 0.8?

**Comment by barche** [comment]
I assume this is no longer a problem, since the listmodel has been entirely rewritten and replaced with `JuliaItemModel`, likely with its own set of new bugs ;)
