### ISSUE TITLE
Qt error of "import org.julialang 1.1"

### ISSUE THREAD

**Issue by sxt-ang** [JuliaGraphics/QML.jl#97]
When I run my QML file,(QT creator,qt5.15.1) on ubuntu, it says"Qml module not found(org.julialang)", and it comes when debug that "qrc:/Page1Form.qml:5:1: module "org.julialang" is not installed qrc:/Page1Form.qml: 5".

I wanna know how to load or install "org.julialang" in QT,thanks!

**Comment by barche** [comment]
The `org.julialang` module is loaded from C++ when starting the QML application from within Julia, how are you trying to start your application?

**Comment by sxt-ang** [comment]
> The `org.julialang` module is loaded from C++ when starting the QML application from within Julia, how are you trying to start your application?

I try to start the application in QT Creator. However it works well when I run it in Julia REPL.

**Comment by Xebit8** [comment]
same here. 
I'm trying to create a basic window app with button for exit from QT. It works just fine.

`import QtQuick 2.2
import QtQuick.Layouts 1.1
import QtQuick.Controls 2.1

ApplicationWindow {
    title: "visible"
    visible: true

    ColumnLayout {
        Text {
            text: "Hello World"
        }
        Button {
            text: "Bye-bye"
            onClicked: Qt.quit()
        }
    }
}`

But as I type "import org.julialang 1.0", I get an error "QML module not found (org.julialang)"

**Comment by barche** [comment]
Yes, you can't load the Julia support from Qt Creator, you need to start the QML application from within Julia, then the org.julialang module will be available on the QML side, e.g:

```julia
using QML
load("qmlfile.qml")
exec()
```

**Comment by ufechner7** [comment]
Perhaps this can be closed now that 0.8 is released?
