### ISSUE TITLE
missing dependency for gltriangle?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaGraphics/QML.jl#99]
When running examples:

```
running example gltriangle.jl...
ERROR: LoadError: ArgumentError: Package ModernGL [66fc600b-dfda-50eb-8b99-91cfa97b1301] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

**Comment by barche** [comment]
Yes, I should streamline instructions to run examples. There is a Project.toml and Manifest.toml in the example directory that should contain what's needed for all the examples.

**Comment by ufechner7** [comment]
In this folder https://github.com/barche/QmlJuliaExamples/tree/master/opengl there is now a Project.toml file that works.
